### ISSUE TITLE
If an attribute is present but no UI is registered, that data will be lost when using Shortcake's edit form

### ISSUE THREAD

**Issue by goldenapples** [wp-shortcake/shortcake#426] opened 2015-08-13 16:33 UTC
See https://github.com/fusioneng/Shortcake/issues/401#issuecomment-130729722

It would good if any attributes not matching attributes could be backed up to hidden model attributes in a similar fashion is was done to unregistered inner content in #424.

**Comment by danielbachhuber** [comment] 2015-08-13 16:38
Dupe of #425

**Closed as completed by danielbachhuber** 2015-08-13 16:38 UTC
