### ISSUE TITLE
Support numeric attribute

### ISSUE THREAD

**Issue by bfintal** [wp-shortcake/shortcake#165] opened 2015-02-17 12:44 UTC
I encountered Jetpack's Googlemap shortcode that has this syntax:

`[googlemaps http://blahblahblah.com]`

It's attribute key is numeric, and by the time the shortcode is rendered into the editor view, the attributes get lost in **js/shortcode-ui.js** `formatShortcode()`. The `$attr` variable inside the `add_shortcode` doesn't contain it anymore

I think this should be handled

**Comment by danielbachhuber** [comment] 2015-02-17 15:19
Duplicate of #128

**Closed as completed by danielbachhuber** 2015-02-17 15:19 UTC

**Comment by bfintal** [comment] 2015-02-17 15:58
Didn't notice that
