### ISSUE TITLE
Editing shortcakes on latest Chrome stopped working

### ISSUE THREAD

**Issue by JCzarnecki** [wp-shortcake/shortcake#593] opened 2016-04-14 13:28 UTC
Hi there,

I have noticed since the latest update of Chrome, at least on a Mac, shortcodes editing stopped working. You open up the edit window but once you save changes, instead of updating the old shortcode, it creates a new one at the very beginning of the post. It is fine on Safari and Firefox.

Please help :(

Best regards and thank you very much in advance!

**Comment by goldenapples** [comment] 2016-04-14 14:00
I believe this issue is a duplicate of #584. Its been reported before, and (if this is the same bug) only happens when the shortcode being edited is the first text in the content. If this is the same issue, can we close this and troubleshoot there?

**Comment by JCzarnecki** [comment] 2016-04-15 07:48
Thanks for a quick reply. It's a different issue. It happens for all shortcodes, no matter what are their positions in the post - in the middle, at the end - it does occur. Is it only me having this issue on the latest Shortcake with the latest Chrome on a Mac?

**Comment by goldenapples** [comment] 2016-04-15 13:50
I don't see that issue in Chrome 50.0.2661.75 (Official Build) (64-bit) using any of the shortcodes from Shortcake Bakery.

Is there anything else about your environment, your WordPress install, or about the shortcodes you're using that could pinpoint the issue?

**Comment by JCzarnecki** [comment] 2016-04-15 14:37
That's interesting. I have just upgraded to 50.0.2661.75 and no longer have this issue!

Although a minute ago I was using Chrome 49.0.2623.110 (64-bit) @ Mac and the bug was occurring on that version. Probably the range of affected versions is a bit bigger (maybe all 49.xxx?), because a few of our site's users were experiencing this problem a couple of days ago.

//EDIT: well, the bug actually still happens sometimes in some circumstances. Will be back with more details soon

**Comment by JCzarnecki** [comment] 2016-04-16 18:40
Ok, after a lot of testing I think I figured what's going on. I noticed that a new shortcode gets inserted at the beginning only if the post's content starts with a shortcode (any). To re-create the bug, please do the following:

1) Add a new post, don't input any content
2) Insert Post Element -> Button -> Insert Element
3) Insert Post Element -> Toggle -> Insert Element
4) Try to edit text of the Toggle (that is placed after the Button). A new Toggle will get inserted at the very beginning.

Now, try to input any text at the beginning, so when you go to Text Mode, you see something like:

`<p class="ui-sortable-handle">some text</p>
[pbs_button label="Click Here" url="#" target="false" align="center" full_width="false"]
[pbs_toggle]CHANGE ME NOW...![/pbs_toggle]`

then switch to Visual Mode and try to edit the toggle - in this case it will work!

Please let me know if it happens on your machine as well? I'm using the latest Chrome 50.0.2661.75 @ Mac. I have tested with two different Wordpress installs.

It seems to be a very similar issue to #584, but it applies to all shortcodes not only the first one in the post, just the first text of the post is what makes the problem.

Do you think there's any chance it could be resolved in a sensible time? We have an editing office of more than 100 editors and it's very urgent for us to get it fixed as they're not tech-savvy at all to be honest and mostly use Chrome. We (the IT dept) advised them to switch to Safari or FF, but they don't like that solution... Unfortunately all the articles start with a shortcode, not with a text and they update a lot of shortcodes daily :(

**Comment by goldenapples** [comment] 2016-04-30 22:23
I believe that this bug has been fixed in WordPress core, with the update to TinyMCE 4.3.10. (At least I can't reproduce it on Chrome 50.0.2661.86.)

Editing posts in Chrome with WP 4.4.2, I see the bug described above and in #584. In 4.5 and 4.5.1, the problem doesn't occur as far as I can tell.

Other than the TinyMCE update in 4.5.1, I can't think offhand of a changeset that would have fixed this. But as I'm unable to reproduce in WP 4.5.x, I'd move to close this issue. Anyone?

**Comment by JCzarnecki** [comment] 2016-05-02 12:58
Great, it works fine again now after the WP upgrade!

**Comment by byheath** [comment] 2016-05-03 05:47
Issue seems to be resolved. Haven't encountered it since upgrading.

**Comment by khromov** [comment] 2016-05-03 09:10
Any possible solution for people stuck on an older version?

**Comment by mattheu** [comment] 2016-06-26 11:18
Still stuck on an older version? Could try and patch this in your install, but since its an upstream TinyMCE or WP MCE Views issue, not sure its easy for us to do.

I'm going to close this issue unless anyone has any ideas.

**Closed as completed by mattheu** 2016-06-26 11:18 UTC
Labels: upstream-bug
