### ISSUE TITLE
Woocommerce conflict

### ISSUE THREAD

**Issue by alexbudin** [wp-shortcake/shortcake#700] opened 2017-02-02 20:59 UTC
Yes, this is a HUGE problem as it cannot be used with WooCommerce. It interferes with all its UI in the backend (WooCoomerce -> Settings)

When can we see a fix? As i made the mistake of updating this plugin and now everything in woocommerce is all over the place. I will have to roll back.

Im using this with ProfilePress and seems that ProfilePress does not work without this. So stupid to set dependencies on something that is badly coded.

Alex

**Comment by southaussienomad** [comment] 2017-02-02 21:24
Here's other people who have reported a conflict between shortcake and woocommerce https://wordpress.org/support/topic/version-0-7-0-interferes-with-woocommerce-products/#post-8731815

**Comment by alexbudin** [comment] 2017-02-02 21:25
The user cpbgroup from there is me :)

**Comment by goldenapples** [comment] 2017-03-29 17:14
I've replied on the .org support ticket. Closing this out as the issue is resolved, but please reopen if you continue to experience conflicts.

**Closed as completed by goldenapples** 2017-03-29 17:14 UTC
